### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by deadlyunicorn** [deadlyunicorn/document-editor#1]
- [ ] Better menu ui.
- [x] Add default colors in the options menu (page bg, text,heading etc.)
- [x] Add character limit so that pages remain consistent
- [ ] add draggable images
- [ ] Maybe sometime in the future add keyboard shortcuts
- [ ] Maybe sometime in the future polish the code
- [x] ADD FONTS. (drop down menu and then google fonts)
- [ ] Maybe add a save button and a select document, that saves or selects the corresponding based on localStorage.(set/get)Item.

**Comment by deadlyunicorn** [comment]
- [ ] Export, Import, Open, options based on txt files? That basically store the array.

**Comment by deadlyunicorn** [comment]
- [ ] Make links work

**Comment by deadlyunicorn** [comment]
Make sure to know people that the page layout is for A4 pages.
